# Generated by Django 6.0.2 on 2026-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0002_document_extracted_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="json_output",
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("TEXT_EXTRACTED", "Text Extracted"),
                    ("EMBEDDING_CREATED", "Embedding Created"),
                    ("INDEXED", "Indexed"),
                    ("LLM_RESPONSE_GENERATED", "LLM Response Generated"),
                    ("FAILED", "Failed"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
