# Generated by Django 6.0.2 on 2026-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
