# Generated by Django 6.0.2 on 2026-02-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0003_remove_document_json_output_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="document",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
    ]
